### ISSUE TITLE
Split lint theme workflow in a new action that would be reused by all our themes

### ISSUE THREAD

**Issue by arzola** [pressbooks/composer-autoupdate-bedrock#52]
- [x] Move the action to a better location
- [x] Make sure it's used in pressbooks-book and all themes
- [x] Write minimal docs for using/updating

See https://github.blog/2023-01-10-introducing-required-workflows-and-configuration-variables-to-github-actions/ for promising approach for this from GitHub

Repo with the first iteration of docs and reusable/required actions:

https://github.com/pressbooks/reusable-workflows

**Comment by SteelWagstaff** [comment]
Needs more detail @arzola

**Comment by SteelWagstaff** [comment]
Merged all but 2 PRs. 
1. Pressbooks/pressbooks has a failing test related to Google Fonts: https://github.com/pressbooks/pressbooks/actions/runs/4176202037/jobs/7234103593. 
2. The lint action is failing in pressbooks-network-analytics: https://github.com/pressbooks/pressbooks-network-analytics/actions/runs/4176097891/jobs/7234109559. @arzola will investigate that one.

**Comment by SteelWagstaff** [comment]
Opened https://github.com/pressbooks/pressbooks-network-analytics/issues/294 as final repo that needs resolution

**Comment by arzola** [comment]
The blocker described above was addressed.
