### ISSUE TITLE
Pressbooks composer update failing on our bedrocks

### ISSUE THREAD

**Issue by fdalcin** [pressbooks/composer-autoupdate-bedrock#60]
Our composer update pipelines started to fail on all our bedrocks

When the update action tries to find the current branch name it fails and throws an exception. Could this be related to the `APP_SINGLE_BRANCH` parameter?

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/1761690/216118495-ed07459d-4391-4c40-be4b-8e3757e6f0db.png">

**Comment by SteelWagstaff** [comment]
For now the workaround is to open the `dev` branch of each relevant bedrock, run `composer update -W` and then commit and push the changes. This will trigger the bedrock based deploy. Ideally this is what our automation would do for us.

**Comment by arzola** [comment]
I Opened a PR in https://github.com/kawax/composer-update-action/pull/636

https://github.com/kawax/composer-update-action/releases/tag/v3.1.1

**Comment by arzola** [comment]
I updated the composer autoupdate bedrock action to use the latest composer update action v3 and it also address the node version scripts upgrade
