### ISSUE TITLE
Fix problem with auto-update routine

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/composer-autoupdate-bedrock#62]
I've noticed a problem with our autoupdate process:

1. In pressbooks/pressbooks, we have a post-commit action for dependabot PRs that autobuilds assets and commits them to the PR: https://github.com/pressbooks/pressbooks/blob/dev/.github/workflows/autobuild-dependabot-assets.yml. The problem here is that the PR cannot be merged because it skips the required 'lint & build assets' steps after this commit has been made. See https://github.com/pressbooks/pressbooks/pull/3206 or screenshot below
![Screenshot from 2023-02-28 11-42-32](https://user-images.githubusercontent.com/13485451/221961557-181f01e3-d49e-4485-a940-4b340856427a.png)

**Comment by SteelWagstaff** [comment]
2 appears to have resolved itself. Maybe was a temporary GitHub issue?

**Comment by arzola** [comment]
We've been having some issues with Dependabot checks, probably related to not being able to access to Composer_PAT

See
https://github.com/pressbooks/pressbooks-results-for-lms/actions/runs/6617376245/job/17973549168?pr=103

https://github.com/dependabot/dependabot-core/issues/5464

**Comment by ho-man-chan** [comment]
Update:
- Researched how these actions are working along with organization workflows.
- Started implementing option 2 of updating bedrock by reading the list of bedrocks.

Questions: For the issue with 'lint & build assets' action, I can't seem to see what it is called. Can someone let me know where it is called?

**Comment by SteelWagstaff** [comment]
@ho-man-chan it's this one: https://github.com/pressbooks/pressbooks/blob/dev/.github/workflows/autobuild-dependabot-assets.yml. I don't think this is the most important issue to adjust, though.

**Comment by SteelWagstaff** [comment]
Superceded by https://github.com/pressbooks/reusable-workflows/issues/8
