### ISSUE TITLE
Fix autoupdate and automerge to work with new branch/PR linting rules

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/composer-autoupdate-bedrock#64]
The commits and PRs automatically created by our composer-autoupdate action no longer pass our globally required branch and PR linting rules. See https://github.com/pressbooks/pressbookspublic-bedrock/pull/569 for a failing PR. 

We should update our composer-autoupdate-bedrock action so that the PR branch name and commits match our new rules (i.e. the branch is called something like `chore/dev-updated` and the commit and PR titles look like `chore: composer update with 4 changes`. See the GIT_COMMIT_PREFIX command available here: https://github.com/kawax/composer-update-action#env. i don't know how to make the branch name match the regex -- i only see a suffix command in the parent action. 

We'll also need to adjust https://github.com/pressbooks/composer-autoupdate-bedrock/blob/028a75871a2de0ccd5e67e2e8ef7de3bf31438f0/.github/workflows/auto-merge.yml#L7

**Comment by arzola** [comment]
WIP https://github.com/pressbooks/composer-autoupdate-bedrock/blob/testingv3/.github/workflows/auto-merge.yml
