### ISSUE TITLE
Automatically update pressbookscom bedrock

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/composer-autoupdate-bedrock#72]
Our composer autoupdate routine hasn't been configured for our pressbookscom-bedrock (used by our marketing website): https://github.com/pressbooks/composer-autoupdate-bedrock/blob/b9aea1e61d395561ecccb928991b2bdc7c8470b9/index.js#L4-L8

It should.

**Comment by arzola** [comment]
I was planning to improve/update this action and also at the same time add the feature to allow us to pass a parameter to trigger special bedrocks like the lti one @SteelWagstaff
